### PR TITLE
add tip when not connected to internet to prevent access

### PR DESCRIPTION
**Pull request by theLMGN**

### CODE REVIEW

**Comment by el-emmo** [comment]
Good suggestion, however you should remove the 'equal length' part because it only needs to be incorrect, length doesn’t matter.

**Comment by theLMGN** [comment]
@el-emmo Good point, however I've noticed that if the password is too short it'll throw a different error, and not even try to connect to it might help to include that

**Comment by el-emmo** [comment]
You're right, in that case I think we should just leave in the bit about equal length.
Also another minor correction, it should be 'an' incorrect password in line 13.

**Comment by theLMGN** [comment]
fixed! thanks for catching that @el-emmo

**Comment by suchmememanyskill** [comment]
The instructions do not list having to change your incorrect password to the correct one. I'm assuming you do want to do that though.

Also just a style thingy: it's probably a better idea to split the sections of no connection and editing a connection 

Like:
- If you want to edit an already existing connection
    1. Do
    2. This
    3. Thing
- if you want to set up a new connection
...

**Comment by thedax** [comment]
Thank you for your contribution, however, this PR has been superceded by https://github.com/nh-server/switch-guide/pull/110, and as such, I will go ahead and close this now.

**Pull request closed without merging**
