### PR TITLE
Add wifi warning to the section before entering RCM

### PR DESCRIPTION
**Pull request by reneroth**
Figured it'd make sense to include the warning on what to do before entering RCM before the part where we enter RCM and not after 😬 
just bit me in the ass, finally managed to enter RCM with my makeshift paperclip jig and then I read about deleting wifi networks on the next page…

### CODE REVIEW

**Comment by el-emmo** [comment]
A paperclip isn’t recommended as that can scratch the pins off. The guide recommends a jig so it is very easy to enter RCM whenever you need to. That’s why I don’t think there’s a problem with mentioning the part about deleting the networks only before making the emuMMC.

**Comment by reneroth** [comment]
Paperclip issue aside, the pre-RCM steps logically seem to belong before the part telling the reader to enter RCM 😬

**Comment by noirscape** [comment]
A. On the main page we have: `It is advised that you read the entire guide from start to finish one or more times before actually running through the guide with your system.`
B. There's little reason to do this, as this guide does not set up the user with any sigpatches, which are the only thing that could cause bans depending on how they're used.

**Comment by thedax** [comment]
I'm not really seeing this as much of an issue either. It doesn't really matter where this suggestion is made, since the acts of entering RCM and pushing a payload can't be detected anyhow (and thus are not bannable).

**Comment by reneroth** [comment]
Thanks for all the extra info! Maybe we could add more detailed information to that section? As it is, it wasn't exactly clear to me why Wifi data needs to be cleared and I thought it was something that'd prevent Atmosphere from booting up correctly. Or maybe it's just me having a hard time understanding stuff 😅

**Comment by noirscape** [comment]
@reneroth - Whilst there's always the risk since Nintendo can adjust their telemetry, if you're not pirating or cheating in online games, you should be fine.

Bans by running homebrew don't happen with Atmosphere, but may happen using other CFWs (which you shouldn't be running to begin with.)

**Pull request closed without merging**
