### PR TITLE
Use ForTheUsers injection website (1/2)

### PR DESCRIPTION
**Pull request by Kore-Development**

### CODE REVIEW

**Comment by el-emmo** [comment]
Why should the website be changed? As far as I can see it’s more or less the same thing.

**Comment by Kore-Development** [comment]
I created a merge request to automatically fetch the latest payloads instead of locally (except for Hekate) and the other one is unmaintained, so there could be issues with the other one in the future.

**Comment by Kore-Development** [comment]
It hasn't been merged yet though

**Comment by el-emmo** [comment]
Going to close this. The webpayload page will not be changed.

**Pull request closed without merging**
